ALTER TABLE Customers DROP FOREIGN KEY FK_Customers_custAddressId
ALTER TABLE Customers DROP FOREIGN KEY FK_Customers_USERID
ALTER TABLE OrderItems DROP FOREIGN KEY FK_OrderItems_orderId
ALTER TABLE Orders DROP FOREIGN KEY FK_Orders_userId
ALTER TABLE Orders DROP FOREIGN KEY FK_Orders_paymentId
ALTER TABLE Suppliers DROP FOREIGN KEY FK_Suppliers_supAddrId
ALTER TABLE Suppliers DROP FOREIGN KEY FK_Suppliers_USERID
ALTER TABLE Item_Category DROP FOREIGN KEY FK_Item_Category_itemId
ALTER TABLE Item_Category DROP FOREIGN KEY FK_Item_Category_catId
ALTER TABLE Suplr_Items DROP FOREIGN KEY FK_Suplr_Items_itemId
ALTER TABLE Suplr_Items DROP FOREIGN KEY FK_Suplr_Items_supId
ALTER TABLE Suplr_Shipper DROP FOREIGN KEY FK_Suplr_Shipper_shipperId
ALTER TABLE Suplr_Shipper DROP FOREIGN KEY FK_Suplr_Shipper_supId
DROP TABLE USERS
DROP TABLE Customers
DROP TABLE CustomerAddress
DROP TABLE CATEGORY
DROP TABLE Items
DROP TABLE OrderItems
DROP TABLE Orders
DROP TABLE PAYMENT
DROP TABLE SHIPPER
DROP TABLE Suppliers
DROP TABLE SUPPLIERADDRESS
DROP TABLE Item_Category
DROP TABLE Suplr_Items
DROP TABLE Suplr_Shipper
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
